# disable python warnings if they annoy you
ignore_warnings: False

# ask user for tags if none are provided in the config
enforce_tags: True

# print warnings for missing configs
print_config_warnings: True

# pretty print config tree at the start of the run using Rich library
print_config: True
